config/routes.rb
Rails.application.routes.draw do
  resources :contact_infos
  resources :contacts do
    resources :contact_infos
  end
  devise_for :users, controllers: { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get "/all_users", to: "users/registrations#allUsers", as: "all_users"
  end
  # Defines the root path route ("/")
  root "contacts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_many :contact_infos
end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :is_admin, :full_name])
  end
end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
  before_action :set_contact_info, only: %i[ show edit update destroy ]

  # GET /contact_infos or /contact_infos.json
  def index
    if user_signed_in?
      @contact = Contact.find(params[:contact_id])
      @contact_infos = @contact.contact_infos
    else
      redirect_to new_user_session_path
    end
  end

  # GET /contact_infos/1 or /contact_infos/1.json
  def show
  end

  # GET /contact_infos/new
  def new
    if user_signed_in?
      @contact = Contact.find(params[:contact_id])
      @contact_info = @contact.contact_infos.build
    else
      redirect_to new_user_session_path, notice: "Sign In Or Sign Up"
    end
  end

  # GET /contact_infos/1/edit
  def edit
  end

  # POST /contact_infos or /contact_infos.json
  def create
    @contact = Contact.find(params[:contact_id])
    @contact_info = @contact.contact_infos.build(contact_info_params)
    respond_to do |format|
      if @contact_info.save
        format.html { redirect_to contact_info_url(@contact_info), notice: "Contact info was successfully created." }
        format.json { render :show, status: :created, location: @contact_info }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_infos/1 or /contact_infos/1.json
  def update
    respond_to do |format|
      if @contact_info.update(contact_info_params)
        format.html { redirect_to contact_info_url(@contact_info), notice: "Contact info was successfully updated." }
        format.json { render :show, status: :ok, location: @contact_info }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_infos/1 or /contact_infos/1.json
  def destroy
    @contact_info.destroy

    respond_to do |format|
      format.html { redirect_to contact_infos_url, notice: "Contact info was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact_info
    @contact_info = ContactInfo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_info_params
    params.require(:contact_info).permit(:contact_id, :info_type, :number)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # protect_from_forgery prepend: true
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /contacts or /contacts.json
  def index
    if user_signed_in?
      @contacts = current_user.contacts
    else
      redirect_to new_user_session_path
    end
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not Authorized To Edit This contact" if @contact.nil?
  end

  # GET /contacts/new
  def new
    if user_signed_in?
      @contact = current_user.contacts.build
    else
      redirect_to new_user_session_path, notice: "Sign In Or Sign Up"
    end
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = current_user.contacts.build(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:full_name, :user_id)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_admin_user!, only: [:new, :create, :allUsers]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :require_no_authentication, except: [:new, :create, :allUsers]

  def allUsers
    @users = User.all
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :is_admin, :full_name])
  end

  def new
    super
  end

  def create
    if current_user.is_admin
      puts "?????????????????????if??????????"
      super
    else
      redirect_to root_path, notice: "Only admins can create new users."
    end
  end

  private

  def authenticate_admin_user!
    if !current_user.is_admin?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_infos_helper.rb
module ContactInfosHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contact_infos/_contact_info.html.erb
<div id="<%= dom_id contact_info %>">
  <p>
    <strong>Contact:</strong>
    <%= contact_info.contact_id %>
  </p>
  <p>
    <strong>Type:</strong>
    <%= contact_info.info_type %>
  </p>
  <p>
    <strong>Number:</strong>
    <%= contact_info.number %>
  </p>
</div>

app/views/contact_infos/_form.html.erb
<%= form_with(model: [contact, contact_info], local: true) do |form| %>
  <% if contact_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact_info.errors.count, "error") %> prohibited this contact info from being saved:</h2>
      <ul>
        <% contact_info.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :info_type %>
    <%= form.text_field :info_type, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :number %>
    <%= form.text_field :number, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit "Add Contact Info", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contact_infos/edit.html.erb
<h1>Editing contact info</h1>

<%= render "form", contact_info: @contact_info %>

<br>

<div>
  <%= link_to "Show this contact info", @contact_info %> |
  <%= link_to "Back to contact infos", contact_infos_path %>
</div>

app/views/contact_infos/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Contact infos</h1>
<div id="contact_infos">
  <% @contact_infos.each do |contact_info| %>
    <%= render contact_info %>
    <p>
      <%= link_to "Show this contact info", contact_info %>
    </p>
  <% end %>
</div>
<%= link_to "New contact info", new_contact_info_path %>

app/views/contact_infos/new.html.erb
  <%= form_with(model: [@contact, @contact_info], local: true) do |form| %>
  <% if @contact_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_info.errors.count, "error") %> prohibited this contact info from being saved:</h2>
      <ul>
        <% @contact_info.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :info_type %>
    <%= form.text_field :info_type, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :number %>
    <%= form.text_field :number, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit "Add Contact Info", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contact_infos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact_info %>

<div>
  <%= link_to "Edit this contact info", edit_contact_info_path(@contact_info) %> |
  <%= link_to "Back to contact infos", contact_infos_path %>

  <%= button_to "Destroy this contact info", @contact_info, method: :delete %>
</div>

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Full name:</strong>
    <%= contact.full_name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= contact.user_id %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>
      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'contacts App',contacts_path,class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%if user_signed_in?%>
        <%if current_user.is_admin%>
          <li class="nav-item">
            <%= link_to 'Create User',  new_user_registration_path,class:'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to 'All User',  all_users_path ,class:'nav-link'%>
          </li>
        <%end%>
        <li class="nav-item">
          <%= link_to 'My contacts', contacts_path,class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Add contact', new_contact_path,class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path,class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", url_for(controller: 'devise/sessions', action: 'destroy', authenticity_token: form_authenticity_token), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to sign out?"},class:'nav-link' %>
        </li>
      <%else%>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path,class:'nav-link'%>
        </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<%= link_to "New contact", new_contact_path %>
<%if user_signed_in?%>
  <h1>contacts</h1>
  <div id="contacts">
    <table class="table table-hover table-striped">
      <thead class="thead">
        <tr class="table-primary">
          <th scope="col">ID</th>
          <th scope="col">Full Name</th>
          <th scope="col">Add contact_info</th>
          <th scope="col">Show contact_info</th>
          <th scope="col">Show contact</th>
          <th scope="col">Edit contact</th>
          <th scope="col">Delete contact</th>
        </tr>
      </thead>
      <tbody>
        <%
    @contacts.each do |contact|
    end
    %>
        <% @contacts.each do |contact| %>
          <tr>
            <td scope="row"><%=contact.id%></td>
            <td><%= contact.full_name%></td>
            <td>
              <%= link_to "Add contact_info",   new_contact_contact_info_path(contact), class: 'btn btn-primary btn-sm' %>
            </td>
            <td>
              <%= link_to "Show contact_info",contact_contact_infos_path(contact), class: 'btn btn-primary btn-sm' %>
            </td>
            <td><%= link_to "Show", contact_path(contact), class: 'btn btn-primary btn-sm' %></td>
            <td><%= link_to "Edit", edit_contact_path(contact),class:'btn btn-warning btn-sm'%></td>
            <td><%= link_to 'Delete', contact_path(contact),  data: { turbo_method: :delete,confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<%end%>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<%= render @contact %>
<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>
  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>
<% render @contact %>
<div class="jumbotron">
  <h1 class="display-4"><%= @contact.full_name.upcase%></h1>
  <hr class="my-4">
  <p class="lead">
    <b>ID:</b> <%= @contact.id%><br/>
  </p>
  <%= link_to "Add contact_info",   new_contact_contact_info_path(@contact), class: 'btn btn-primary btn-sm' %>
  <%= link_to "Edit this contact", edit_contact_path(@contact),class:'btn btn-primary' %> |
  <%= link_to "Back to contacts", contacts_path,class:'btn btn-warning' %>
  <%= link_to 'Delete', @contact,  data: { turbo_method: :delete,confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>ContactAppInRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'contacts/header'%>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alert' %><br />
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>